USE [MsTrials]
GO

/****** Object:  Table [dbo].[Autor]    Script Date: 18/05/2015 11:37:54 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Newsletter](
	[NewsletterId] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](256) NULL
 CONSTRAINT [PK_Newsletters] PRIMARY KEY CLUSTERED 
(
	[NewsletterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO