//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTrials.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorEstudio
    {
        public int AutorEstudioId { get; set; }
        public int EstudioId { get; set; }
        public int AutorId { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Estudio Estudio { get; set; }
    }
}
