//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTrials.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autore
    {
        public Autore()
        {
            this.AutoresEstudios = new HashSet<AutoresEstudio>();
        }
    
        public int AutorId { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Reseña { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<AutoresEstudio> AutoresEstudios { get; set; }
    }
}
