//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTrials.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudios
    {
        public int EstudioId { get; set; }
        public string Titulo { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Revision { get; set; }
        public Nullable<short> Volumen { get; set; }
    }
}
