//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTrials.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudio
    {
        public Estudio()
        {
            this.AutorEstudios = new HashSet<AutorEstudio>();
        }
    
        public int EstudioId { get; set; }
        public string Titulo { get; set; }
        public Nullable<short> Año { get; set; }
        public string Revision { get; set; }
        public string Volumen { get; set; }
        public string Objetivos { get; set; }
        public string Metodo { get; set; }
        public string Resultados { get; set; }
        public string Conclusion { get; set; }
        public string NombreComercial { get; set; }
        public Nullable<int> MedicamentoId { get; set; }
        public Nullable<int> IndicacionId { get; set; }
        public Nullable<int> ComparadorId { get; set; }
        public Nullable<long> CantidadVisitas { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Nombre { get; set; }
        public string Link { get; set; }
        public int PrimerAutorId { get; set; }
        public Nullable<int> SponsorId { get; set; }
        public string ImageURL { get; set; }
        public int Active { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual ICollection<AutorEstudio> AutorEstudios { get; set; }
        public virtual Comparador Comparador { get; set; }
        public virtual Indicacion Indicacion { get; set; }
        public virtual Medicamento Medicamento { get; set; }
        public virtual Sponsor Sponsor { get; set; }
    }
}
