//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTrials.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public Sponsor()
        {
            this.Estudios = new HashSet<Estudio>();
        }
    
        public int SponsorId { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Estudio> Estudios { get; set; }
    }
}
